services:
  scanservjs:
    build:
      context: .
      target: scanservjs-core
    container_name: scanservjs
    env_file:
      - .env
    volumes:
      - ./scans:/var/lib/scanservjs/output
      - ./config:/etc/scanservjs
    ports:
      - 8080:8080
    network_mode: host
